language: ruby

dist: trusty

matrix:
  include:
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord4_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord4_2.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord4_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord4_2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord4_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord4_2.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord4_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord4_2.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord4_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord4_2.gemfile

    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_0.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_0.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_0.gemfile

    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_1.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_1.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_1.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_1.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_1.gemfile
      env: USE_MYSQL=true
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_1.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_1.gemfile
      env: USE_MYSQL=true
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_1.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_1.gemfile
      env: USE_MYSQL=true
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_1.gemfile

    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord5_2.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord5_2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord5_2.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord5_2.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_2.gemfile
      env: USE_MYSQL=true
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord5_2.gemfile

    - rvm: 2.5.7
      gemfile: gemfiles/activerecord6_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord6_0.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord6_0.gemfile
      env: USE_MYSQL=true
    - rvm: 2.6.5
      gemfile: gemfiles/activerecord6_0.gemfile

services:
  - mysql

before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

git:
  depth: 1
